### ISSUE TITLE
detailed design layout

### ISSUE THREAD

**Issue by Troy-Lawson** [gctools-outilsgc/profile_service_react#11]

**Comment by Troy-Lawson** [comment]
implementing the UI layer. visual styles colors and spaceing

**Comment by MPM9000** [comment]
PDF file of detailed screen walkthrough covering proposed visual design, getting started wizard, & dimensions.[Directory_Service_01_New_User_v05.pdf](https://zube.io/files/tbs-sct/cedc8e5ffa2f68113723cf1ac507a735-directory_service_01_new_user_v05.pdf)

**Comment by MPM9000** [comment]
v05 PDF file of detailed screen walkthrough covering proposed UI, visual design, getting started wizard, & dimensions. PDF & Adobe Illustrator file will be posted in Profile channel on message for added measure. @piet0024 

[Directory_Service_01_New_User_v05.pdf](https://zube.io/files/tbs-sct/5541367ce4e747e96bd3fc46319fc921-directory_service_01_new_user_v05.pdf)

**Comment by MPM9000** [comment]
https://github.com/gctools-outilsgc/profile_service_react/commit/845d0d0fe8539b989250a0047e697fc22fa14742

@piet0024 @Steph4104

**Comment by MPM9000-zz** [comment]
[US01_Directory_Service_v09.pdf](https://zube.io/files/tbs-sct/2cfeb2ef9b9b22b8345a92b3f91cd90c-us01_directory_service_v09.pdf)

**Comment by MPM9000-zz** [comment]
More refinement work done to help guide the interface work & moved all work to UX prototypes folder

Directory Interface Design guide: 
https://github.com/gctools-outilsgc/ux_prototypes/tree/master/Directory_Service/Directory_User_Interfaces

User Stories 01 (New User) & 12 (Supervisor creates a team) :
https://github.com/gctools-outilsgc/ux_prototypes/tree/master/Directory_Service/Directory_User_Stories

@piet0024 @Steph4104

**Comment by MPM9000-zz** [comment]
Current bttns & icons need to be increased in size to 48 x 48px to accurately reflect touch area for responsive/mobile. This also impacts screen layouts throughout the entire user story & taskflow.  See card #3500 & #3501
