### ISSUE TITLE
create wizard state

### ISSUE THREAD

**Issue by Troy-Lawson** [gctools-outilsgc/profile_service_react#12]
needs to be further broke down further

**Comment by Troy-Lawson** [comment]
on boarding, state for creating a new profile and editing a profile

**Comment by piet0024** [comment]
Create and modify various functionality from the mock ups and task flows
- [ ] Move supervisor picker and team picker into the team component
- [ ] Create wizard edit modal
- [ ] Create new user wizard walk through

**Comment by Troy-Lawson** [comment]
closed in favor of epic
