### ISSUE TITLE
copy and translation

### ISSUE THREAD

**Issue by Troy-Lawson** [gctools-outilsgc/profile_service_react#13]

**Comment by Troy-Lawson** [comment]
we need translations back and reviewed by Gen

**Comment by MGoodberry** [comment]
[DirectoryCreateWizard.xlsx](https://zube.io/files/tbs-sct/87089e4090345c86615262f97c6fb045-directorycreatewizard.xlsx)

Copy for first user task flow

**Comment by MGoodberry** [comment]
@LemieuxGen
