### ISSUE TITLE
Creating and translating copy for profile

### ISSUE THREAD

**Issue by Troy-Lawson** [gctools-outilsgc/profile_service_react#17]
check on progress

**Comment by MGoodberry** [comment]
@LemieuxGen First draft for copy in word doc. [OnboardingWizard.docx](https://zube.io/files/tbs-sct/afe674dc9c5f2b1a73d659a4b0154ed9-onboardingwizard.docx)  Illustrator pdf also included just to show roughly where the text would go. [US01_Directory_New_User_Onboarding_DS_step Text update.pdf](https://zube.io/files/tbs-sct/2bc68d83a6b0a53d5b8c76412e903863-us01_directory_new_user_onboarding_ds_step-text-update.pdf) file also included just to show roughly where the text would go.

**Comment by MGoodberry** [comment]
@LemieuxGen First draft for copy in word doc.[OnboardingWizard.docx](https://zube.io/files/tbs-sct/37feceb7f201a42456b853a79a99f2c3-onboardingwizard.docx) Illustrator pdf also included just to show roughly where the text would go. [US01_Directory_New_User_Onboarding_DS_step Text update.pdf](https://zube.io/files/tbs-sct/6f36840ca182cc5158ee2c526f65fc54-us01_directory_new_user_onboarding_ds_step-text-update.pdf)

**Comment by MGoodberry** [comment]
First draft. Illustrator pdf just included to show roughly where text would go.[OnboardingWizard.docx](https://zube.io/files/tbs-sct/37feceb7f201a42456b853a79a99f2c3-onboardingwizard.docx)[US01_Directory_New_User_Onboarding_DS_step Text update.pdf](https://zube.io/files/tbs-sct/6f36840ca182cc5158ee2c526f65fc54-us01_directory_new_user_onboarding_ds_step-text-update.pdf)

**Comment by MGoodberry** [comment]
[OnboardingWizard.docx](https://zube.io/files/tbs-sct/37feceb7f201a42456b853a79a99f2c3-onboardingwizard.docx) Word doc. verison

**Comment by LemieuxGen** [comment]
@marianneaubrey15 here's the updated Word doc with my comments in tracked changes. Please see note at the end about the site notice.
[Copy GCprofile Wizard.docx](https://zube.io/files/tbs-sct/c56a95aa824c5756a7e145c9d15c43f7-copy-gcprofile-wizard.docx)

**Comment by MGoodberry** [comment]
Sent to translation

**Comment by MGoodberry** [comment]
Received from translation. Need final review of French text before sending to Nick. [Final French Onboarding Wizard.DOCX](https://zube.io/files/tbs-sct/c1c9c1272e8f9df0f966c537678d1b18-final-french-onboarding-wizard.docx)

**Comment by MGoodberry** [comment]
@LemieuxGen Final French text from Nathan [Onboard Wizard Text Nathan French Final.DOCX](https://zube.io/files/tbs-sct/f194c1f502b71f63ff64eb92807ab6d4-onboard-wizard-text-nathan-french-final.docx)

**Comment by LemieuxGen** [comment]
[Copy GCprofile Wizard_FR.docx](https://github.com/gctools-outilsgc/profile_service_react/files/2633348/Copy.GCprofile.Wizard_FR.docx)
updated file, with minor changes.
