### ISSUE TITLE
Building form validation

### ISSUE THREAD

**Issue by Troy-Lawson** [gctools-outilsgc/profile_service_react#19]
checking form inputs for bad stuff
question on where validation occurs: back end or front end?

**Comment by MPM9000-zz** [comment]
Not sure what is expected of me on this. Need me to test the directory onboarding? Please drop me a note here. Thanks. 

Meantime some initial research:
https://uxdesign.cc/design-better-forms-96fadca0f49c

**Comment by bryan-robitaille** [comment]
Validation will occur on both backend and front end.  Backend validation is needed as a back up to front end validation given that multiple applications *could* modify a users profile.

-Fields that need validation:
* Email
* Phone Number's (mobile and office) when passed to PaaS should only be numeric chars.

-Mandatory Fields:
* Name
* Email

**Comment by piet0024** [comment]
I added html5 required and pattern validation on the Name, Email and Phone Number inputs. https://github.com/gctools-outilsgc/profile_service_react/commit/c2d4b3921d29505ad1b7d03de82bd39874f3c3fd
