### ISSUE TITLE
research app flow logic and make a decision on trigger for wizard

### ISSUE THREAD

**Issue by Troy-Lawson** [gctools-outilsgc/profile_service_react#20]
when and where to show the wizard
determine requirements for showing wizard

**Comment by piet0024** [comment]
Brain dump:
I'm trying to think of the best way to trigger the user onboarding. I have 2 possible solutions.

1. When the user visits the application we query their profile and see what information is missing (we have email and name from account, so we test for job title, address, phone, supervisor, team). However if the user has one of these fields not completed (currently we do not require any information from the onboarding module. Let's say a user has gone through the onboarding module and did not fill out some information, their supervisor is not in the system etc.) they will be redirected to the onboarding module every time they visit the application. 

2. We create a new field or micro service that saves if the user has completed the onboard module. We query the new field / service when the user visits the application and redirect accordingly. When the user clicks "finish" or "start" we toggle the onboard field to false.

I'm sure there is a better solution and I'm just having a brain fart.

**Comment by piet0024** [comment]
As for when to trigger the onboard redirect I'll look at hooking in to login or when the application gets authorised through the single sign-on

**Comment by massierick** [comment]
Could the onboarding become portion of the profile badge count? IE, once completed, it generates a badge. Then when users log on, the system checks to see if they have the Onboarding badge - if they do, the script doesn't run.

**Comment by bryan-robitaille** [comment]
I like the second option because it removes the need for intense business logic from the front end.  We could easily implement a new query on PaaS something along the lines of onboardProfile(gcId="1234"){onboard} which returns a boolean... "data":{"onboardProfile":{"onboard": true}}.  Given that PaaS in the authoritative source of profile info it would make sense to have this query as it wouldn't be a one off.

**Comment by bryan-robitaille** [comment]
To also add to that solution by driving the onboarding buisness logic as the PaaS level we could then easily modify the onboarding trigger as needed which would impact all apps and not have to recode them seperately.

**Comment by piet0024** [comment]
If we can assume our other apps have onboarding / tutorials / tour modules, I wonder if there is value in creating a service that will keep track of what users have done what modules across apps.

**Comment by bryan-robitaille** [comment]
Interesting.. wondering if a stand alone service is really necessary or if we just build a query for each service instead.  Then in the app/service that would display (I'm assuming badges... or overall profile completion) it could either query the services it's reporting against individually or if we want to get really fancy we can 'stitch' graphql schemas together to query PaaS to report against core apps.

**Comment by piet0024** [comment]
So we will hook into the login function (which will also trigger with the single sign-on if the user is logged on, visiting from another app) and it will check for something along the lines of "onboardProfile" from PaaS and redirect the user to the onboarding module. When the user clicks"start" or "finish view profile" we'll set the "onboardProfile" data in PaaS.

Thanks everyone for helping me work this out. 👌
