### ISSUE TITLE
research snapshot tests

### ISSUE THREAD

**Issue by Troy-Lawson** [gctools-outilsgc/profile_service_react#26]
research into snapshot tests. How and why to use them

**Comment by piet0024** [comment]
https://medium.freecodecamp.org/how-to-build-sturdy-react-apps-with-tdd-and-the-react-testing-library-47ad3c5c8e47

https://www.apollographql.com/docs/react/recipes/testing.html

https://blog.kentcdodds.com/introducing-the-react-testing-library-e3a274307e65

**Comment by piet0024** [comment]
https://facebook.github.io/create-react-app/docs/running-tests
