### ISSUE TITLE
Create beta (closed) test scenario

### ISSUE THREAD

**Issue by Troy-Lawson** [gctools-outilsgc/profile_service_react#38]

**Comment by piet0024** [comment]
WIP Test Scenario Ideas:

I believe the goal of this testing should be to see if users can perform some of the basic editing tasks on the app.

1. Capture or give instruction on user's device and browser
 1. If we choose to capture this data we will need to ensure that we match each response to identify device and browser specific issues.
1. Create or login into an existing account on dev.account
 1. We will need the user to create or have an existing account on dev.account in order for them to edit their profile
1. At this point we can either ask the user to navigate to their own profile (see how they do it) OR we can ask them to visit the onboarding module to fill out their profile
 1. IF WE GO ONBOARDING
  1. we may ask them to navigate to /onboarding (provide them the link or ask them to get there, there is a link on the home page)
  1. Have the user go through the onboarding module and report their experience.
 1. IF WE ASK THEM TO EDIT NORMALLY
  1. Ask user to navigate to their own profile to edit information (test if user's can find their own profile)
  1. Ask user to edit their phone numbers, office numbers and maybe avatar
  1. Ask user to find and report to their supervisor
