### ISSUE TITLE
Notifications of events

### ISSUE THREAD

**Issue by bryan-robitaille** [gctools-outilsgc/profile_service_react#6]
Various events in profile as a service will need to be generated.  The front end application will need a way to trigger notifications of these events.

This issue is for discussion on how possible system designs that could be used to implement. For example:
- Design a notification micro service that can be called by any application and handles notifications for the workspace.
- Same as above but build notifications as part of profile as a service
- Design notifications as part of each service

**Comment by pandurx** [comment]
[Requirements Analysis Document - GCconnex Notifications_v1.docx](https://github.com/gctools-outilsgc/profile_service_react/files/2160281/Requirements.Analysis.Document.-.GCconnex.Notifications_v1.docx)

Here is the requirements analysis document for the notifications (legacy). Give or take, some requirements may be transferable to the new system.
