### ISSUE TITLE
load testing profile

### ISSUE THREAD

**Issue by Troy-Lawson** [gctools-outilsgc/profile_service_react#8]
load testing profile. Attempt to crash system and analyse what fails and when.

**Comment by Troy-Lawson** [comment]
stress test of system

**Comment by erickasr2** [comment]
@bryan-robitaille do we need to prepare a message to users for if/when you're successful crashing the system?

**Comment by bryan-robitaille** [comment]
*Drum role......*
**And the winner is....**
.
.
.
.
.
*~ pause for dramtic effect ~*
.
.
.
.
.
**Graphql Yoga and Prisma by a landslide!!!!!!**

Test was run under the following conditions to remove Network and OS issues:
* Both solutions were run containerized in docker
* Tests were conducted on the same dev laptop with no other applications running
* Bother were tested using identical artillery.io scripts

**Setup**

2 scenarios were defined in the script:
1. App creates a profile, waits 3 seconds, queries the profile, waits 3 seconds, modifies the profile, waits 3 seconds, and then deletes the profile.
2. App queries for five random profiles

Traffic was defined in 3 stages:
Low: (60 second duration)
* Starts with 5 scenarios starting per second and ramps up to 50 scenarios per second

Medium: (60 second duration)
* Starts with 50 scenarios starting per second and ramps up to 200 scenarios per second

High: (60 second duration)
* Continues the creation of 200 scenarios per second until end of test.

**Results**
*Comparison key facts:*

Metric | Graphql Yoga & Prisma | Python Django
-------- | ------------------------------- | -------------------------
*Latency* 
Max | 1.3 seconds | 89 seconds
Median | 8.3 ms | 445 ms
P95 | 41.8 ms | 16 seconds
P99 | 199 ms | 39 seconds
*Reset Connections*| 0 | 8912
*Scenario Completion | 100% | 58%


**Document Reports**
[yoga_results_basic.json.html](https://zube.io/files/tbs-sct/86207946675bd5bb002b4c5e50a02b74-yoga_results_basic-json.html)

[django_basic.json.html](https://zube.io/files/tbs-sct/a56e533714fd1c469ba13cebd06db9ac-django_basic-json.html)
